name: Snazzy LookML Linter 
author: 
description: Lint LookML Projects and create Pull Request reviews with linting violations.

inputs:
  configFile: # id of input
    description: "path to lookml project"
    required: true
    default: "config.example.yaml"
#   lookMlProject: # id of input
#     description: "path to lookml project"
#     required: true
#     default: "."

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.configFile }}
#     - ${{ inputs.lookMlProject }}

